receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_http/traces:
    endpoint: http://tempo:4318
  otlp_http/metrics:
    endpoint: http://prometheus:9090/api/v1/otlp

processors:
  batch:
  k8s_attributes:
    wait_for_metadata: true
    pod_association:
      - sources:
        - from: resource_attribute
          name: k8s.pod.ip


service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      processors: [k8s_attributes, batch]
      exporters: [otlp_http/traces]
    metrics:
      receivers: [otlp]
      processors: [k8s_attributes, batch]
      exporters: [otlp_http/metrics]
